### ISSUE TITLE
can't load Albert-large-v2 config

### ISSUE THREAD

**Issue by ra312** [rajammanabrolu/Q-BERT#1]
Good morning, everyone,

After I ran the command

**_python run_squad.py --model_type albert --model_name_or_path albert-large-v2 --do_train  --train_file data/cleaned_qa_train.json --predict_file data/cleaned_qa_dev.json --per_gpu_eval_batch_size 8 --learning_rate 3e-5 --max_seq_length 512 --doc_stride 128 --output_dir ./models/ --warmup_steps 814 --max_steps 8144 --version_2_with_negative --gradient_accumulation_steps 24 --overwrite_output_dir_**

I get the following exception

**06/20/2020 03:20:12 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "/anaconda/envs/qbert/lib/python3.7/site-packages/transformers/configuration_utils.py", line 251, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_squad.py", line 581, in <module>
    main()
  File "run_squad.py", line 500, in main
    config = AlbertConfig.from_pretrained(args.model_name_or_path + "/config.json")
  File "/anaconda/envs/qbert/lib/python3.7/site-packages/transformers/configuration_utils.py", line 200, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/anaconda/envs/qbert/lib/python3.7/site-packages/transformers/configuration_utils.py", line 270, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load 'albert-large-v2/config.json'. Make sure that:

- 'albert-large-v2/config.json' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'albert-large-v2/config.json' is the correct path to a directory containing a 'config.json' file**

I tried to google it, but with no success. Could anyone advice me what is wrong?

**Comment by ra312** [comment]
It might be something to do with alberta-v2-large version.

**Comment by poetienshul** [comment]
Thanks for pointing this out, there was a small bug in the training code where it was pulling from the wrong pre-trained location. I've merged a fix for this issue.

**Comment by ra312** [comment]
Hi, 
Thanks for fixing it, I ran the command just now and it went well except for a runtime error in loading state_dict for AlbertForQuestionAnswering.
The command is 
**python run_squad.py --model_type albert --model_name_or_path albert-xxlarge-v1 --do_train  --train_file data/cleaned_qa_train.json --predict_file data/cleaned_qa_dev.json --per_gpu_eval_batch_size 8 --learning_rate 3e-5 --max_seq_length 512 --doc_stride 128 --output_dir ./models/ --warmup_steps 814 --max_steps 8144 --version_2_with_negative --gradient_accumulation_steps 24 --overwrite_output_dir**
The error message I get is 
**RuntimeError: Error(s) in loading state_dict for AlbertForQuestionAnswering:
	size mismatch for albert.encoder.embedding_hidden_mapping_in.weight: copying a param with shape torch.Size([4096, 128]) from checkpoint, the shape in current model is torch.Size([1024, 128]).
	size mismatch for albert.encoder.embedding_hidden_mapping_in.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.full_layer_layer_norm.weight: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.full_layer_layer_norm.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.query.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.query.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.key.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.key.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.value.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.value.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.dense.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.dense.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.weight: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.ffn.weight: copying a param with shape torch.Size([16384, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 1024]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.ffn.bias: copying a param with shape torch.Size([16384]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.ffn_output.weight: copying a param with shape torch.Size([4096, 16384]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
	size mismatch for albert.encoder.albert_layer_groups.0.albert_layers.0.ffn_output.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for albert.pooler.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for albert.pooler.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([1024]).**
It seems a simple shape mismatch in the pickled model. If I wanted to fix it, it would require re-training of the model, right?

**Comment by poetienshul** [comment]
Ah, our original intention was for this to really work with albert-large-v2. I've added another small fix to make the input model more flexible, and should work now with other huggingface pretrained models. Let me know if you run into any other issues.

**Comment by poetienshul** [comment]
However, doing this may bring up other issues later down the pipeline for the rest of the code, so we highly recommend just sticking with the albert-large-v2 model anyway!

**Comment by ra312** [comment]
Hi poetienshul, 
Thanks for the fix. Yes, I am sticking with albert-large-v2 and the command finished normally.
As a next step (from the README), I ran this command
**python train.py --rom_file_path ./extraction/z-machine-games-master/autoplay-game-suite/zork1.z5 --tsv_file ../data/zork1_entity2id.tsv --attr_file attrs/zork1_attr.txt --training_type chained --reward_type game_and_IM**
However, it seems train.py is looking for model's checkpoints.

**Traceback (most recent call last):
  File "train.py", line 135, in <module>
    trainer = QBERTTrainer(params)
  File "/home/ra312/sandbox/Q-BERT/qbert/intrinsic_qbert.py", line 58, in __init__
    os.mkdir(self.chkpt_path)
FileNotFoundError: [Errno 2] No such file or directory: './models/checkpoints'**

Is it expected or I did something wrong ?
Rauan.

**Comment by poetienshul** [comment]
Yeah, the model just needs another dir to write checkpoints to.

**mkdir models && mkdir models/checkpoints**

**Comment by ra312** [comment]
Hi,
Now, I have another runtime exception, please help,

**Traceback (most recent call last):
  File "train.py", line 135, in <module>
    trainer = QBERTTrainer(params)
  File "/home/ra312/sandbox/Q-BERT/qbert/intrinsic_qbert.py", line 78, in __init__
    self.cur_reload_state = env.get_state()
AttributeError: 'FrotzEnv' object has no attribute 'get_state'**
The command is the same as above

**Comment by rajammanabrolu** [comment]
This looks like an issue with Jericho simulator https://github.com/microsoft/jericho I suggest you update it to version 2.4.2 as listed in the readme. The `environment.yml` has also been updated
